services:
  web:
    build:
      context: ..
      dockerfile: web_8_autolodge/Dockerfile
      args:
        ENABLE_DYNAMIC_V1: ${ENABLE_DYNAMIC_V1:-false}
        ENABLE_DYNAMIC_V2: ${ENABLE_DYNAMIC_V2:-false}
        ENABLE_DYNAMIC_V3: ${ENABLE_DYNAMIC_V3:-false}
        ENABLE_DYNAMIC_V4: ${ENABLE_DYNAMIC_V4:-false}
        API_URL: ${API_URL:-http://app:8090}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8090}
        GIT_COMMIT_HASH: ${GIT_COMMIT_HASH:-unknown}
    ports:
      - "127.0.0.1:${WEB_PORT}:8007"
    restart: always
    environment:
      - API_URL=${API_URL:-http://app:8090}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8090}
      - PORT=8007
      - NODE_ENV=production
      - ENABLE_DYNAMIC_V1=${ENABLE_DYNAMIC_V1:-false}
      - NEXT_PUBLIC_ENABLE_DYNAMIC_V1=${ENABLE_DYNAMIC_V1:-false}
      - ENABLE_DYNAMIC_V2=${ENABLE_DYNAMIC_V2:-false}
      - NEXT_PUBLIC_ENABLE_DYNAMIC_V2=${ENABLE_DYNAMIC_V2:-false}
      - ENABLE_DYNAMIC_V3=${ENABLE_DYNAMIC_V3:-false}
      - NEXT_PUBLIC_ENABLE_DYNAMIC_V3=${ENABLE_DYNAMIC_V3:-false}
      - ENABLE_DYNAMIC_V4=${ENABLE_DYNAMIC_V4:-false}
      - NEXT_PUBLIC_ENABLE_DYNAMIC_V4=${ENABLE_DYNAMIC_V4:-false}
    networks:
      - apps_net

networks:
  apps_net:
    external: true
