services:
  web:
    build:
      context: ...
      dockerfile: web_1_autocinema/Dockerfile
      args:
        ENABLE_DYNAMIC_V1: ${ENABLE_DYNAMIC_V1:-false}
        ENABLE_DYNAMIC_V2_AI_GENERATE: ${ENABLE_DYNAMIC_V2_AI_GENERATE:-false}
        ENABLE_DYNAMIC_V2_DB_MODE: ${ENABLE_DYNAMIC_V2_DB_MODE:-false}
        ENABLE_DYNAMIC_V3: ${ENABLE_DYNAMIC_V3:-false}
        ENABLE_DYNAMIC_V4: ${ENABLE_DYNAMIC_V4:-false}
        API_URL: ${API_URL:-http://app:8080}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8090}

    ports:
      - "127.0.0.1:${WEB_PORT}:8000"
    restart: always
    environment:
      - API_URL=${API_URL:-http://app:8080}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8090}
      - PORT=8000
      - NODE_ENV=production
      - ENABLE_DYNAMIC_V1=${ENABLE_DYNAMIC_V1:-false}
      - NEXT_PUBLIC_ENABLE_DYNAMIC_V1=${ENABLE_DYNAMIC_V1:-false}
      - ENABLE_DYNAMIC_V2_AI_GENERATE=${ENABLE_DYNAMIC_V2_AI_GENERATE:-false}
      - NEXT_PUBLIC_ENABLE_DYNAMIC_V2_AI_GENERATE=${ENABLE_DYNAMIC_V2_AI_GENERATE:-false}
      - ENABLE_DYNAMIC_V2_DB_MODE=${ENABLE_DYNAMIC_V2_DB_MODE:-false}
      - NEXT_PUBLIC_ENABLE_DYNAMIC_V2_DB_MODE=${ENABLE_DYNAMIC_V2_DB_MODE:-false}
      - ENABLE_DYNAMIC_V3=${ENABLE_DYNAMIC_V3:-false}
      - NEXT_PUBLIC_ENABLE_DYNAMIC_V3=${ENABLE_DYNAMIC_V3:-false}
      - ENABLE_DYNAMIC_V4=${ENABLE_DYNAMIC_V4:-false}
      - NEXT_PUBLIC_ENABLE_DYNAMIC_V4=${ENABLE_DYNAMIC_V4:-false}
    networks:
      - apps_net

networks:
  apps_net:
    external: true
