services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENABLE_DYNAMIC_HTML: ${ENABLE_DYNAMIC_HTML:-false}
        DEFAULT_SEED_STRUCTURE: ${DEFAULT_SEED_STRUCTURE:-1}
        DYNAMIC_HTML_STRUCTURE: ${DYNAMIC_HTML_STRUCTURE:-false}
    ports:
      - "127.0.0.1:${WEB_PORT}:8009"
    restart: always
    environment:
      - API_URL=http://app:8080
      - PORT=8009
      - NODE_ENV=production
      - ENABLE_DYNAMIC_HTML=${ENABLE_DYNAMIC_HTML:-false}
      - NEXT_PUBLIC_ENABLE_DYNAMIC_HTML=${ENABLE_DYNAMIC_HTML:-false}
      - NEXT_PUBLIC_DEFAULT_SEED_STRUCTURE=${DEFAULT_SEED_STRUCTURE:-1}
      - DYNAMIC_HTML_STRUCTURE=${DYNAMIC_HTML_STRUCTURE:-false}
      - NEXT_PUBLIC_DYNAMIC_HTML_STRUCTURE=${DYNAMIC_HTML_STRUCTURE:-false}
    networks:
      - apps_net

networks:
  apps_net:
    external: true
